# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/vjt/documents/Code/github/video_transcription

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/vjt/documents/Code/github/video_transcription

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vjt/documents/Code/github/video_transcription/CMakeFiles /mnt/c/Users/vjt/documents/Code/github/video_transcription//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vjt/documents/Code/github/video_transcription/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WhisperTest

# Build rule for target.
WhisperTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WhisperTest
.PHONY : WhisperTest

# fast build rule for target.
WhisperTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/build
.PHONY : WhisperTest/fast

external/whisper_common/common-ggml.o: external/whisper_common/common-ggml.cpp.o
.PHONY : external/whisper_common/common-ggml.o

# target to build an object file
external/whisper_common/common-ggml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.o
.PHONY : external/whisper_common/common-ggml.cpp.o

external/whisper_common/common-ggml.i: external/whisper_common/common-ggml.cpp.i
.PHONY : external/whisper_common/common-ggml.i

# target to preprocess a source file
external/whisper_common/common-ggml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.i
.PHONY : external/whisper_common/common-ggml.cpp.i

external/whisper_common/common-ggml.s: external/whisper_common/common-ggml.cpp.s
.PHONY : external/whisper_common/common-ggml.s

# target to generate assembly for a file
external/whisper_common/common-ggml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.s
.PHONY : external/whisper_common/common-ggml.cpp.s

external/whisper_common/common-sdl.o: external/whisper_common/common-sdl.cpp.o
.PHONY : external/whisper_common/common-sdl.o

# target to build an object file
external/whisper_common/common-sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.o
.PHONY : external/whisper_common/common-sdl.cpp.o

external/whisper_common/common-sdl.i: external/whisper_common/common-sdl.cpp.i
.PHONY : external/whisper_common/common-sdl.i

# target to preprocess a source file
external/whisper_common/common-sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.i
.PHONY : external/whisper_common/common-sdl.cpp.i

external/whisper_common/common-sdl.s: external/whisper_common/common-sdl.cpp.s
.PHONY : external/whisper_common/common-sdl.s

# target to generate assembly for a file
external/whisper_common/common-sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.s
.PHONY : external/whisper_common/common-sdl.cpp.s

external/whisper_common/common.o: external/whisper_common/common.cpp.o
.PHONY : external/whisper_common/common.o

# target to build an object file
external/whisper_common/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.o
.PHONY : external/whisper_common/common.cpp.o

external/whisper_common/common.i: external/whisper_common/common.cpp.i
.PHONY : external/whisper_common/common.i

# target to preprocess a source file
external/whisper_common/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.i
.PHONY : external/whisper_common/common.cpp.i

external/whisper_common/common.s: external/whisper_common/common.cpp.s
.PHONY : external/whisper_common/common.s

# target to generate assembly for a file
external/whisper_common/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.s
.PHONY : external/whisper_common/common.cpp.s

external/whisper_common/grammar-parser.o: external/whisper_common/grammar-parser.cpp.o
.PHONY : external/whisper_common/grammar-parser.o

# target to build an object file
external/whisper_common/grammar-parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.o
.PHONY : external/whisper_common/grammar-parser.cpp.o

external/whisper_common/grammar-parser.i: external/whisper_common/grammar-parser.cpp.i
.PHONY : external/whisper_common/grammar-parser.i

# target to preprocess a source file
external/whisper_common/grammar-parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.i
.PHONY : external/whisper_common/grammar-parser.cpp.i

external/whisper_common/grammar-parser.s: external/whisper_common/grammar-parser.cpp.s
.PHONY : external/whisper_common/grammar-parser.s

# target to generate assembly for a file
external/whisper_common/grammar-parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.s
.PHONY : external/whisper_common/grammar-parser.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.s
.PHONY : main.cpp.s

modules/speech_processing.o: modules/speech_processing.cpp.o
.PHONY : modules/speech_processing.o

# target to build an object file
modules/speech_processing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/speech_processing.cpp.o
.PHONY : modules/speech_processing.cpp.o

modules/speech_processing.i: modules/speech_processing.cpp.i
.PHONY : modules/speech_processing.i

# target to preprocess a source file
modules/speech_processing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/speech_processing.cpp.i
.PHONY : modules/speech_processing.cpp.i

modules/speech_processing.s: modules/speech_processing.cpp.s
.PHONY : modules/speech_processing.s

# target to generate assembly for a file
modules/speech_processing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/speech_processing.cpp.s
.PHONY : modules/speech_processing.cpp.s

modules/transcriber.o: modules/transcriber.cpp.o
.PHONY : modules/transcriber.o

# target to build an object file
modules/transcriber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/transcriber.cpp.o
.PHONY : modules/transcriber.cpp.o

modules/transcriber.i: modules/transcriber.cpp.i
.PHONY : modules/transcriber.i

# target to preprocess a source file
modules/transcriber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/transcriber.cpp.i
.PHONY : modules/transcriber.cpp.i

modules/transcriber.s: modules/transcriber.cpp.s
.PHONY : modules/transcriber.s

# target to generate assembly for a file
modules/transcriber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/transcriber.cpp.s
.PHONY : modules/transcriber.cpp.s

modules/utils.o: modules/utils.cpp.o
.PHONY : modules/utils.o

# target to build an object file
modules/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/utils.cpp.o
.PHONY : modules/utils.cpp.o

modules/utils.i: modules/utils.cpp.i
.PHONY : modules/utils.i

# target to preprocess a source file
modules/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/utils.cpp.i
.PHONY : modules/utils.cpp.i

modules/utils.s: modules/utils.cpp.s
.PHONY : modules/utils.s

# target to generate assembly for a file
modules/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/utils.cpp.s
.PHONY : modules/utils.cpp.s

modules/video_handler.o: modules/video_handler.cpp.o
.PHONY : modules/video_handler.o

# target to build an object file
modules/video_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/video_handler.cpp.o
.PHONY : modules/video_handler.cpp.o

modules/video_handler.i: modules/video_handler.cpp.i
.PHONY : modules/video_handler.i

# target to preprocess a source file
modules/video_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/video_handler.cpp.i
.PHONY : modules/video_handler.cpp.i

modules/video_handler.s: modules/video_handler.cpp.s
.PHONY : modules/video_handler.s

# target to generate assembly for a file
modules/video_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/modules/video_handler.cpp.s
.PHONY : modules/video_handler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WhisperTest"
	@echo "... external/whisper_common/common-ggml.o"
	@echo "... external/whisper_common/common-ggml.i"
	@echo "... external/whisper_common/common-ggml.s"
	@echo "... external/whisper_common/common-sdl.o"
	@echo "... external/whisper_common/common-sdl.i"
	@echo "... external/whisper_common/common-sdl.s"
	@echo "... external/whisper_common/common.o"
	@echo "... external/whisper_common/common.i"
	@echo "... external/whisper_common/common.s"
	@echo "... external/whisper_common/grammar-parser.o"
	@echo "... external/whisper_common/grammar-parser.i"
	@echo "... external/whisper_common/grammar-parser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/speech_processing.o"
	@echo "... modules/speech_processing.i"
	@echo "... modules/speech_processing.s"
	@echo "... modules/transcriber.o"
	@echo "... modules/transcriber.i"
	@echo "... modules/transcriber.s"
	@echo "... modules/utils.o"
	@echo "... modules/utils.i"
	@echo "... modules/utils.s"
	@echo "... modules/video_handler.o"
	@echo "... modules/video_handler.i"
	@echo "... modules/video_handler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

