# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/vjmar/Documents/1. Code/github/video_transcription"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/vjmar/Documents/1. Code/github/video_transcription"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/vjmar/Documents/1. Code/github/video_transcription/CMakeFiles" "/mnt/c/Users/vjmar/Documents/1. Code/github/video_transcription/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/vjmar/Documents/1. Code/github/video_transcription/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WhisperTest

# Build rule for target.
WhisperTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WhisperTest
.PHONY : WhisperTest

# fast build rule for target.
WhisperTest/fast:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/build
.PHONY : WhisperTest/fast

external/whisper_common/common-ggml.o: external/whisper_common/common-ggml.cpp.o

.PHONY : external/whisper_common/common-ggml.o

# target to build an object file
external/whisper_common/common-ggml.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.o
.PHONY : external/whisper_common/common-ggml.cpp.o

external/whisper_common/common-ggml.i: external/whisper_common/common-ggml.cpp.i

.PHONY : external/whisper_common/common-ggml.i

# target to preprocess a source file
external/whisper_common/common-ggml.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.i
.PHONY : external/whisper_common/common-ggml.cpp.i

external/whisper_common/common-ggml.s: external/whisper_common/common-ggml.cpp.s

.PHONY : external/whisper_common/common-ggml.s

# target to generate assembly for a file
external/whisper_common/common-ggml.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-ggml.cpp.s
.PHONY : external/whisper_common/common-ggml.cpp.s

external/whisper_common/common-sdl.o: external/whisper_common/common-sdl.cpp.o

.PHONY : external/whisper_common/common-sdl.o

# target to build an object file
external/whisper_common/common-sdl.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.o
.PHONY : external/whisper_common/common-sdl.cpp.o

external/whisper_common/common-sdl.i: external/whisper_common/common-sdl.cpp.i

.PHONY : external/whisper_common/common-sdl.i

# target to preprocess a source file
external/whisper_common/common-sdl.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.i
.PHONY : external/whisper_common/common-sdl.cpp.i

external/whisper_common/common-sdl.s: external/whisper_common/common-sdl.cpp.s

.PHONY : external/whisper_common/common-sdl.s

# target to generate assembly for a file
external/whisper_common/common-sdl.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common-sdl.cpp.s
.PHONY : external/whisper_common/common-sdl.cpp.s

external/whisper_common/common.o: external/whisper_common/common.cpp.o

.PHONY : external/whisper_common/common.o

# target to build an object file
external/whisper_common/common.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.o
.PHONY : external/whisper_common/common.cpp.o

external/whisper_common/common.i: external/whisper_common/common.cpp.i

.PHONY : external/whisper_common/common.i

# target to preprocess a source file
external/whisper_common/common.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.i
.PHONY : external/whisper_common/common.cpp.i

external/whisper_common/common.s: external/whisper_common/common.cpp.s

.PHONY : external/whisper_common/common.s

# target to generate assembly for a file
external/whisper_common/common.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/common.cpp.s
.PHONY : external/whisper_common/common.cpp.s

external/whisper_common/grammar-parser.o: external/whisper_common/grammar-parser.cpp.o

.PHONY : external/whisper_common/grammar-parser.o

# target to build an object file
external/whisper_common/grammar-parser.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.o
.PHONY : external/whisper_common/grammar-parser.cpp.o

external/whisper_common/grammar-parser.i: external/whisper_common/grammar-parser.cpp.i

.PHONY : external/whisper_common/grammar-parser.i

# target to preprocess a source file
external/whisper_common/grammar-parser.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.i
.PHONY : external/whisper_common/grammar-parser.cpp.i

external/whisper_common/grammar-parser.s: external/whisper_common/grammar-parser.cpp.s

.PHONY : external/whisper_common/grammar-parser.s

# target to generate assembly for a file
external/whisper_common/grammar-parser.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/external/whisper_common/grammar-parser.cpp.s
.PHONY : external/whisper_common/grammar-parser.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/main.cpp.s
.PHONY : main.cpp.s

speech_processing.o: speech_processing.cpp.o

.PHONY : speech_processing.o

# target to build an object file
speech_processing.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/speech_processing.cpp.o
.PHONY : speech_processing.cpp.o

speech_processing.i: speech_processing.cpp.i

.PHONY : speech_processing.i

# target to preprocess a source file
speech_processing.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/speech_processing.cpp.i
.PHONY : speech_processing.cpp.i

speech_processing.s: speech_processing.cpp.s

.PHONY : speech_processing.s

# target to generate assembly for a file
speech_processing.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/speech_processing.cpp.s
.PHONY : speech_processing.cpp.s

transcriber.o: transcriber.cpp.o

.PHONY : transcriber.o

# target to build an object file
transcriber.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/transcriber.cpp.o
.PHONY : transcriber.cpp.o

transcriber.i: transcriber.cpp.i

.PHONY : transcriber.i

# target to preprocess a source file
transcriber.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/transcriber.cpp.i
.PHONY : transcriber.cpp.i

transcriber.s: transcriber.cpp.s

.PHONY : transcriber.s

# target to generate assembly for a file
transcriber.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/transcriber.cpp.s
.PHONY : transcriber.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/utils.cpp.s
.PHONY : utils.cpp.s

video_handler.o: video_handler.cpp.o

.PHONY : video_handler.o

# target to build an object file
video_handler.cpp.o:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/video_handler.cpp.o
.PHONY : video_handler.cpp.o

video_handler.i: video_handler.cpp.i

.PHONY : video_handler.i

# target to preprocess a source file
video_handler.cpp.i:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/video_handler.cpp.i
.PHONY : video_handler.cpp.i

video_handler.s: video_handler.cpp.s

.PHONY : video_handler.s

# target to generate assembly for a file
video_handler.cpp.s:
	$(MAKE) -f CMakeFiles/WhisperTest.dir/build.make CMakeFiles/WhisperTest.dir/video_handler.cpp.s
.PHONY : video_handler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... WhisperTest"
	@echo "... external/whisper_common/common-ggml.o"
	@echo "... external/whisper_common/common-ggml.i"
	@echo "... external/whisper_common/common-ggml.s"
	@echo "... external/whisper_common/common-sdl.o"
	@echo "... external/whisper_common/common-sdl.i"
	@echo "... external/whisper_common/common-sdl.s"
	@echo "... external/whisper_common/common.o"
	@echo "... external/whisper_common/common.i"
	@echo "... external/whisper_common/common.s"
	@echo "... external/whisper_common/grammar-parser.o"
	@echo "... external/whisper_common/grammar-parser.i"
	@echo "... external/whisper_common/grammar-parser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... speech_processing.o"
	@echo "... speech_processing.i"
	@echo "... speech_processing.s"
	@echo "... transcriber.o"
	@echo "... transcriber.i"
	@echo "... transcriber.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... video_handler.o"
	@echo "... video_handler.i"
	@echo "... video_handler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

